# SPECIALTIES/CLASSES
STUNNER = "STUNNER"
ATTACKER = "ATTACKER"
SUPPORTER = "SUPPORTER"
ANOMALY = "ANOMALY"
DEFENDER = "DEFENDER"

# ATTRIBUTES
ETHER = "ETHER"
ELECTRIC = "ELECTRIC"
FIRE = "FIRE"
FROST = "FROST"
ICE = "ICE"
PHYSICAL = "PHYSICAL"

# FACTIONS
BELOBOG_HEAVY_INDUSTRIES = "BELOBOG HEAVY INDUSTRIES"
CUNNING_HARES = "CUNNING HARES"
NEPS = "NEPS"
OBOLS_SQUAD = "OBOLS SQUAD"
SECTION_6 = "SECTION 6"
STARS_OF_LYRA = "STARS OF LYRA"
VICTORIA_HOUSEKEEPING = "VICTORIA HOUSEKEEPING"

# STATS
TYPE_BONUS_DMG = "bonus"
TYPE_CRIT_RATE = "crit rate"
TYPE_CRIT_DMG = "crit dmg"